# config/_default/languages.yml
# Configuration file for Hugo
# See https://gohugo.io/getting-started/configuration/ for details

en:
  languageCode: en
  languageName: English
  contentDir: content/en
