# config/_default/languages.yml
# Configuration file for Hugo
# See https://gohugo.io/getting-started/configuration/ for details

en:
  languageCode: en
  languageName: English
  contentDir: content/en

fr:
  languageCode: fr
  languageName: Français
  contentDir: content/fr

zh-hant:
  languageCode: zh-hant
  languageName: 繁體中文
  contentDir: content/zh-hant
