# config/_default/menu.yml
# Configuration file for Hugo
# See https://gohugo.io/getting-started/configuration/ for details

main:
  - name: About
    url: '#about'
    weight: 1
  - name: Resume
    url: documents/cv.pdf
    weight: 2
  - name: Posts
    url: posts/
    weight: 3
