# .github/workflows/gh-pages.yml
# GitHub Actions configuration file for publishing hugo site
# See https://github.com/chabad360/hugo-gh-pages for details

name: publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Publish site
        uses: chabad360/hugo-gh-pages@v2
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          cname: ragonneau.co
          branch: main
          repo: ragonneau/ragonneau.github.io
